---
_target_: flwr.server.strategy.FedAvg # points to FedAvg (as if you were doing it in your python file)
fraction_fit: 0.00001
min_fit_clients: ${num_clients_per_round_fit} # you can refer to any other variable defined in the config (as long as it is part of the experiment you run)
fraction_evaluate: 0.00001
min_evaluate_clients: ${num_clients_per_round_eval} # this is a reference to the setting defined in `conf/base.yaml`
min_available_clients: ${num_clients}
on_fit_config_fn: # this is a function
  _target_: server.get_on_fit_config
  config: ${config_fit}
# we could define here evaluate_fn, but since it requires arguments
# that are defined at runtime (e.g. the test loader), let's better
# do it in the main
