_target_: clients.client.iba_client_fn
_recursive_ : false
cfg:
  model: ${model}
  optimizers: ${optimizers}
  config_fit:
    lr: ${config_fit.lr}
  poisoned_batch_size: ${poisoned_batch_size}
  poisoned_target: ${poisoned_target}
  batch_size: ${batch_size}
  norm_scaling_factor: 1.2
  dataset:
    size: ${dataset.size}
  mask_grad: ${mask_grad}
  pgd_conf: ${pgd}