_target_: clients.client.randomized_simple_poisoned_client_fn
_recursive_ : false
cfg:
  model: ${model}
  optimizers: ${optimizers}
  poisoned_batch_size: ${poisoned_batch_size}
  poisoned_target: ${poisoned_target}
  batch_size: ${batch_size}
  patch_size_range: 
    - ${as_tuple:2, 7}  
    - ${as_tuple:2, 7}
  patch_location_range:
    - ${as_tuple:0, 10}
    - ${as_tuple:0, 10}
  patch_val: 1 
  norm_scaling_factor: 1.2
  grad_filter: ${grad_filter}
  pgd_conf: ${pgd_conf}
  global_seed: ${global_seed}
  poison_between: ${poison_between}