---

num_rounds: 2
num_clients: 4
num_classes: 10
num_clients_per_round_fit: 2
num_clients_per_round_eval: 2

batch_size: 16
global_seed: 42
valratio: 0.15

num_cpus_per_client: 1
num_gpus_per_client: 0

poisoned_clients_ratio: 0
poisoned_batch_size: ${batch_size}
poisoned_target: 1

pgd:
  active: true
  eps: 0.03
  norm_type: "inf"

config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 2

config_eval: # condif availabvle when evaluating
  lr: 0.01
  momentum: 0.9
  local_epochs: 2

wandb:
  active: true
  report_clients: false
  group_name: null
  main_run_name: null
  
defaults:
  - partitioners: iid
  - model: mobilenet
  - strategy: fedavg
  - dataset: mnist
  - optimizers: sgd  
  - poisoned_client: iba