---

num_rounds: 2
num_clients: 4
num_clients_per_round_fit: 2
num_clients_per_round_eval: 2

batch_size: 16
global_seed: 42
valratio: 0.15

num_cpus_per_client: 1
num_gpus_per_client: 0

poisoned_clients_ratio: 0
poisoned_batch_size: ${batch_size}
poisoned_target: 1

pgd_conf:
  active: true
  eps: 1.0
  norm_type: "inf"

poison_between:
  - ${as_tuple:5,50}

ray_auto: false

grad_filter:
  active: true
  filter:
    _target_: poisoning_transforms.model.masks.neurotoxin_poisoner.NeuroToxinPoisoner
    ratio: 0.94

config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 2

config_eval: ${config_fit}

evaluate_metrics_aggregation_fn: true

wandb:
  active: true
  report_clients: false
  group_name: null
  main_run_name: null
  project_name: "federated-2"
  
defaults:
  - partitioners: iid
  - model: mobilenet
  - strategy: fedavg
  - dataset: mnist
  - optimizers: sgd  
  - poisoned_client: iba
  - global_merger: single
  - defense_strategy: no_defense