---

num_rounds: 5
num_clients: 12
batch_size: 16
num_classes: 10
num_clients_per_round_fit: 4
num_clients_per_round_eval: 2
config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1

defaults:
  - model: net
  - strategy: fedavg # points to conf/strategy/fedavg.yaml